export const allMaids = [
  {
    id: "1",
    name: "Farjana",
    rating: 5.0,
    reviews: 176,
    job: ["Cook", "Baby Sitter"],
    age: 48,
    experience: 5,
    Nationality: "Indian",
    imageURI:
    "https://plus.unsplash.com/premium_photo-1661634777510-e6e56b312604?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bWFpZHxlbnwwfHwwfHx8MA%3D%3D",
    religion: "Muslim",
    maritalStatus: "Married",
    gender: "Female",
    availability:"Long-term",
    verified: true,
    language: ["Hindi", "English"],
    petFriendly: "Yes",
    expectedSalary: "₹20,000/month",
    location: "Mumbai, Maharashtra",
    note: "Expert in North Indian and Mughlai cuisine, also great with babies.",
  },
  {
    id: "2",
    imageURI:"https://media.gettyimages.com/id/1419360594/photo/woman-loading-the-washing-machine-with-laundry.jpg?s=612x612&w=gi&k=20&c=xtHjsljqSgxzm6A9aRHDA50FyirmG233evGSsVTcX-E=", 
    name: "Aisha",
    rating: 4.8,
    reviews: 20,
    job: ["Cleaner"],
    age: 35,
    Nationality: "Indian",
    experience: 3,
    availability:"Short-term",
    religion: "Hindu",
    maritalStatus: "Single",
    gender: "Female",
    verified: false,
    language: ["Tamil"],
    petFriendly: "No",
    expectedSalary: "₹15,000/month",
    location: "Chennai, Tamil Nadu",
    note: "Experienced in deep cleaning and maintaining household hygiene.",
  },
  {
    id: "3",
    name: "Ramesh",
    rating: 4.5,
    availability:"Long-term",
    reviews: 50,
    job: ["Cook"],
    age: 40,
    Nationality: "Indian",
    experience: 10,
    imageURI:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs07dYqfgGeDowvzYmIFqf7DwVpXpsUDIUIw&s",
    religion: "Hindu",
    maritalStatus: "Married",
    gender: "Male",
    verified: true,
    language: ["Hindi", "English"],
    petFriendly: "Yes",
    expectedSalary: "₹22,000/month",
    location: "Delhi, Delhi",
    note: "Specializes in vegetarian South Indian and North Indian dishes.",
  },
  {
    id: "4",
    name: "Sandeep",
    rating: 4.2,
    reviews: 32,
    job: ["Cleaner", "Kitchen Helper"],
    age: 30,
    experience: 4,
    religion: "Sikh",
    Nationality: "Indian",
    maritalStatus: "Single",
    imageURI:
    "https://cleanmethod.com/wp-content/uploads/2022/09/What-Happens-During-A-Rough-Construction-Cleaning-1.jpg",
    availability:"Short-term",
    gender: "Male",
    verified: false,
    language: ["Punjabi", "Hindi"],
    petFriendly: "Yes",
    expectedSalary: "₹17,000/month",
    location: "Amritsar, Punjab",
    note: "Hardworking and detail-oriented in household and kitchen work.",
  },
  {
    id: "5",
    name: "Kavita",
    rating: 4.9,
    availability:"Long-term",
    reviews: 89,
    job: ["Baby Sitter"],
    age: 29,
    experience: 6,
    religion: "Christian",
    maritalStatus: "Married",
    gender: "Female",
    Nationality: "Indian",
    verified: true,
    imageURI:"https://thumbs.dreamstime.com/b/young-pretty-smiling-nanny-playing-two-girls-sitting-floor-woman-building-towers-two-adorable-girls-135353126.jpg",
    language: ["English", "Hindi"],
    petFriendly: "No",
    expectedSalary: "₹18,000/month",
    location: "Bangalore, Karnataka",
    note: "Loving and patient with kids, experienced in newborn care.",
  },
  {
    id: "6",
    name: "Sunita",
    rating: 4.6,
    reviews: 41,
    job: ["Top Work", "Cleaner"],
    availability:"Short-term",
    age: 38,
    experience: 8,
    religion: "Jain",
    imageURI:"https://media.istockphoto.com/id/1057339828/photo/happy-young-hispanic-woman-is-babysitting-tutoring-elementary-age-girl.jpg?s=612x612&w=0&k=20&c=0_hqmdmV8O4N_h2Z_4Ip-O_OZFMgRSrinG66iI86vu8=",
    maritalStatus: "Divorced",
    Nationality: "Indian",
    gender: "Female",
    verified: false,
    language: ["Hindi"],
    petFriendly: "Yes",
    expectedSalary: "₹16,000/month",
    location: "Jaipur, Rajasthan",
    note: "Efficient and thorough in house cleaning and dusting.",
  },
  {
    id: "7",
    name: "Rahul",
    rating: 4.3,
    reviews: 25,
    job: ["Cook", "Cleaner"],
    availability:"Long-term",
    age: 36,
    experience: 5,
    religion: "Muslim",
    imageURI:
    "https://5.imimg.com/data5/SELLER/Default/2022/3/YM/BE/IJ/148640419/restaurant-cook-service-500x500.jpg",
    maritalStatus: "Single",
    gender: "Male",
    language: ["Hindi", "Urdu"],
    Nationality: "Indian",
    verified: true,
    petFriendly: "No",
    expectedSalary: "₹19,000/month",
    location: "Hyderabad, Telangana",
    note: "Can cook both veg and non-veg dishes; good at cleaning work.",
  },
  {
    id: "8",
    name: "Geeta",
    rating: 4.7,
    availability:"Short-term",
    reviews: 55,
    job: ["Baby Sitter"],
    age: 33,
    experience: 7,
    imageURI:"https://mymaidandcookservices.com/images/cook-maid-services.webp", 
    religion: "Buddhist",
    Nationality: "Indian",
    maritalStatus: "Married",
    gender: "Female",
    verified: false,
    language: ["Hindi", "Bengali"],
    petFriendly: "Yes",
    expectedSalary: "₹21,000/month",
    location: "Kolkata, West Bengal",
    note: "Loves children, ensures their safety, and engages them in activities.",
  },
  {
    id: "9",
    name: "Priya",
    rating: 4.8,
    reviews: 74,
    job: ["Cook", "Kitchen Helper"],
    age: 28,
    imageURI:"https://mymaidandcookservices.com/images/house-maid-cook.jpg",   
    Nationality: "Indian",
    experience: 4,
    religion: "Hindu",
    availability:"Long-term",
    maritalStatus: "Married",
    gender: "Female",
    verified: true,
    language: ["Tamil", "Hindi"],
    petFriendly: "Yes",
    expectedSalary: "₹20,000/month",
    location: "Coimbatore, Tamil Nadu",
    note: "Good at assisting in the kitchen and preparing delicious meals.",
  },
  {
    id: "10",
    name: "Vikram",
    rating: 4.4,
    reviews: 38,
    imageURI:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJLFIgLoTTjYH-xwohMRKXFjdvuCCGLBr2Aw&s",
    job: ["Cleaner", "Top Work"],
    availability:"Short-term",
    Nationality: "Indian",
    age: 42,
    experience: 9,
    religion: "Sikh",
    maritalStatus: "Divorced",
    gender: "Male",
    verified: false,
    language: ["Punjabi", "English"],
    petFriendly: "No",
    expectedSalary: "₹17,500/month",
    location: "Ludhiana, Punjab",
    note: "Highly professional in cleaning and maintaining house interiors.",
  },
  {
    id: "11",
    name: "Anjali",
    imageURI:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTViUyO2ybiCIFXgiGExgwDMcrz83sWQehQYQ&s", 
    Nationality: "Indian",
    rating: 4.6,
    reviews: 67,
    job: ["Baby Sitter", "Cook"],
    age: 31,
    experience: 5,
    availability:"Long-term",
    religion: "Christian",
    maritalStatus: "Single",
    gender: "Female",
    verified: true,
    language: ["English", "Hindi"],
    petFriendly: "Yes",
    expectedSalary: "₹22,500/month",
    location: "Pune, Maharashtra",
    note: "Can take care of children and also prepare healthy meals for them.",
  },
  {
    id: "12",
    name: "Deepak",
    rating: 4.5,
    Nationality: "Indian",
    reviews: 30,
    imageURI:
    "https://media.istockphoto.com/id/1398819667/photo/young-african-american-male-householder-loading-washing-machine.jpg?s=612x612&w=0&k=20&c=dIqdRMva6OEDBngPLvV6RzCe7xvy0qPV-YYlBLa5mZ4=",
    job: ["Kitchen Helper"],
    availability:"Short-term",
    age: 39,
    experience: 7,
    religion: "Jain",
    maritalStatus: "Married",
    gender: "Male",
    verified: false,
    language: ["Hindi"],
    petFriendly: "Yes",
    expectedSalary: "₹18,500/month",
    location: "Ahmedabad, Gujarat",
    note: "Good at assisting in cooking, chopping, and kitchen maintenance.",
  },
  {
    id: "13",
    name: "Meera",
    rating: 4.9,
    reviews: 80,
    job: ["Cook"],
    imageURI:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7VcCxICB8htX2kvAqmXZbViUJeG3llNHNIQ&s",
    age: 34,
    availability:"Long-term",
    experience: 6,
    religion: "Hindu",
    maritalStatus: "Married",
    Nationality: "Indian",
    gender: "Female",
    verified: true,
    language: ["Hindi", "Telugu"],
    petFriendly: "No",
    expectedSalary: "₹21,500/month",
    location: "Vijayawada, Andhra Pradesh",
    note: "Expert in home-style cooking, especially South Indian dishes.",
  },
  {
    id: "14",
    name: "Suraj",
    rating: 4.3,
    reviews: 29,
    job: ["Cleaner"],
    age: 37,
    imageURI:"https://thumbs.dreamstime.com/b/content-young-man-doing-laundry-holding-basket-standing-next-to-washing-machine-isolated-white-background-64912927.jpg",
    experience: 5,
    religion: "Muslim",
    Nationality: "Indian",
    maritalStatus: "Single",
    gender: "Male",
    availability:"Short-term",
    verified: false,
    language: ["Hindi", "English"],
    petFriendly: "Yes",
    expectedSalary: "₹16,500/month",
    location: "Nagpur, Maharashtra",
    note: "Diligent cleaner with expertise in floor and upholstery cleaning.",
  },
  {
    id: "15",
    name: "Neha",
    availability:"Long-term",
    rating: 4.7,
    reviews: 52,
    job: ["Baby Sitter"],
    age: 30,
    experience: 6,
    religion: "Buddhist",
    imageURI:"https://static.vecteezy.com/system/resources/previews/027/004/305/large_2x/portrait-of-asian-female-cleaning-service-staff-in-uniform-and-rubber-gloves-housework-concept-photo.jpg",
    maritalStatus: "Divorced",
    gender: "Female",
    language: ["Hindi", "English"],
    petFriendly: "No",
    verified: true,
    Nationality: "Indian",
    expectedSalary: "₹19,000/month",
    location: "Bhopal, Madhya Pradesh",
    note: "Compassionate with children, ensures their well-being and happiness.",
  },
];